import { Inter } from "next/font/google";
import { ThemeContextProvider } from "../context/ThemeContext";
import { ThemeProvider } from "../providers/ThemeProvider";
import { Footer } from "./components/footer/Footer";
import { Navbar } from "./components/navbar/Navbar";
import "./globals.css";
import AuthProvider from "../providers/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "next blog ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <ThemeContextProvider>
            <ThemeProvider>
              <div className="min-h-screen bg-bg text-textColor">
                <div className="max-w-screen-2xl ml-auto mr-auto px-[80px]">
                  <Navbar />
                  {children}
                  <Footer />
                </div>
              </div>
            </ThemeProvider>
          </ThemeContextProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
